ecomproject/ecoapp/urls.py
from django.urls import path 
from .views import *
app_name = "ecoapp"
from .import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url



urlpatterns = [
    #customer url patterns
    path("", views.index, name="index"),
    path("r'^home3/?$'", views.home3, name="home3"),
    path("aboutus/",views.aboutus, name="aboutus"),
   
    path("r'^addcomment/<int:id>/?$'", views.addcomment, name="addcomment"),
    path("contact/", views.contact, name="contact"),
    
    path("home",HomeView.as_view(),name="home"),
    
   
   
    path("about",AboutView.as_view(),name="about"),
    
    path("allproducts/", AllProductView.as_view(),name="allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(),name="productdetail"),
    path("product2/<slug:slug>/", ProductDetailPageView.as_view(),name="productdetailpage2"),
    
    
    

    path("add-to-cart-<int:pro_id>", AddToCartView.as_view(),name="addtocart"),
    
    path("my-cart",MyCartView.as_view(),name="mycart"),
   
    
    path("manage-cart/<int:cp_id>/",ManageCartView.as_view(),name="managecart"),
    
    path("empty-cart", EmptyCartView.as_view(),name="emptycart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path("index",views.index, name="index"),
    path("register",CustomerRegistrationView.as_view(), name="customerregistration"),
    path("logout",CustomerLogoutView.as_view(), name ="customerlogout"),
    path("login/",CustomerLoginView.as_view(), name ="customerlogin"),
    
    path("profile/",CustomerProfileView.as_view(), name ="customerprofile"),
    path("profile/order-<int:pk>/",CustomerOrderDetailView.as_view(),name="customerorderdetail"),
    path("search/", SearchView.as_view(),name="search"),
    path("search2/", SearchBaseView.as_view(),name="searchbase"),
    path("forgot-password/", PasswordForgotView.as_view(), name="passwordforgot"),
    path("password-reset/<email>/<token>/", PasswordResetView.as_view(), name="passwordreset"),



    #admin url pattern
    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-message/",AdminMessageView.as_view(),name="adminmessage"),
    path("admin-home/", AdminHomeView.as_view(),name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),name="orderdetailpage"),
    path("admin-all-orders/", AdminOrderListView.as_view(),name="adminorderlist"),
    path("admin-order-<int:pk>-change/", AdminOrderStatusChangeView.as_view(),name="adminorderstatuschange"),
    path("admin-product-list/", AdminProductView.as_view(), name="adminproductlist"),
    path("admin-product/add/",AdminProductCreateView.as_view(), name ="adminproductcreate"),
    path("productupdate/<pk>/", ProductUpdateView.as_view(), name="product-update"),
    path("products_delete/<int:id>/delete/", product_delete_view, name="product-delete"),
    path("adminlogout",AdminLogoutView.as_view(), name ="adminlogout"),


    #####for wish-list purpose#####################################################################################3
    path("wishlist1/add_to_wishlist/<int:id>/",views.add_to_wishlist, name = "user_wishlist"),
    
    path("wishlist", views.wishlist, name = "wishlist"),
   
   


  
    
]

ecomproject/ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("ecoapp.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomproject/ecoapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.conf import settings


# Create your models here.
class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile  = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username




class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)#onetoone give the object name directly
    
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.full_name








class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)




    @staticmethod
    def get_all_categories():
        return Category.objects.all()
   




    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to="products")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    
    
    warranty = models.CharField(max_length=300,null=True , blank=True)
    warranty_policy = models.CharField(max_length=300,null=True , blank=True)
    view_count = models.PositiveIntegerField(default=0)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)

    @staticmethod
    def get_all_products():
        return Product.objects.all()

    @staticmethod
    def get_all_products_by_categoryid(category_id):
        if category_id:
            return Product.objects.filter(category = category_id)
        
        else:
            return Product.get_all_products()
    


    def __str__(self):
        return self.title

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to = "products/images/")
    
    def __str__(self):
        return self.product.title




class Cart(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return "Cart:" + str(self.id)






class CartProduct(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    rate = models.PositiveIntegerField()

    def __str__(self):
        return "Cart:" + str(self.cart.id) + "CartProduct:" +str(self.id)

ORDER_STATUS = (
    ("Order Received", "Order Received"),# this is one of the property given by the django and first is stored in database and another is shon in the form
    ("Order Processing", "Order Processing"),
    ("On the Way", "on the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)
METHOD = (
    ("Cash On Delivery","Cash On Delivery"),
    ("Khalti Payment","Khalti Payment"),

)

class Order(models.Model):
    
    cart= models.OneToOneField(Cart, on_delete=models.CASCADE)
    order_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null = True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices = ORDER_STATUS, default="Order Received")
    created_at = models.DateTimeField(auto_now=True)
    payment_method = models.CharField(max_length=20, choices = METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(default = False, null= True, blank=True)
    def __str__(self):
        return "Order:" + str(self.id)


class Wish(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, null=True, blank=True)
    email = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return "Wish:" + str(self.id)

class WishProduct(models.Model):
    wish = models.ForeignKey(Wish,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    rate = models.PositiveIntegerField() 

    def __str__(self):
        return "Wish:" + str(self.wish.id) + "WishProduct:" +str(self.id)
    
   













class Comment(models.Model):
    STATUS = (
        ('New','New'),
        ('True','True'),
        ('False','False'),
    )
    product=models.ForeignKey(Product, related_name="comments",on_delete=models.CASCADE)
 
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    
    subject = models.CharField(max_length=50, blank=True)
    comment = models.CharField(max_length=250, blank=True)
    rate = models.IntegerField(default=1)
    ip = models.CharField(max_length=20, blank=True)
    status = models.CharField(max_length=10, choices=STATUS,default='New')
    create_at = models.DateTimeField(auto_now=True)
    update_at = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.user)



  


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']
        
class Contact(models.Model):
    identity = models.CharField(max_length=50, blank=True)
    email = models.EmailField()
    number = models.PositiveIntegerField()
    message = models.TextField()


    def __str__(self):
        return self.identity

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['identity', 'email', 'number','message']

ecomproject/templates/allproducts.html
{% extends "base.html" %}
{% block title %}All Products {% endblock %}
{% block content %}

    <div class="container">
        <h3>All Products</h3>
        <hr>
        {% for cat in allcategories %}
        <h4>{{cat.title}}</h4>

        <div class="row">
            {% for p in cat.product_set.all %}
            <div class="col-md-4">
                <div class="m-4">
                    <h4><a href="{% url 'ecoapp:productdetail' p.slug %}">{{p.title}}</a></h4>
                    <img src="{{p.image.url}}" alt="default" class="img-fluid" style="height:250px; object-fit:cover;">
                    <p class="mt-3">Price: <strike> Rs.{{p.marked_price}}</strike> Rs. {{p.selling_price}} </p>
                    <a href="{% url 'ecoapp:addtocart' p.id %}" class="btn btn-primary" >Add to Cart</a>
                    <hr>
                </div>
            </div>
            {%endfor%}
           
        </div>
        {%endfor%}
    </div>

{% endblock %}

ecomproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="{% static 'home/assets/css/style1.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'home/assets/css/zoom.css' %}" />
    
<body>
    
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
          <a class="navbar-brand" href="#"><img src="{% static 'home/images/large.png'%} " style="height: 80px; border-radius:50%" ></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'ecoapp:index' %}"><i class="fa fa-home"></i>Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ecoapp:home' %}"><i class="fa fa-shirtsinbulk"></i>Store</a>
                  </li>
                  
                
                
                
                
                <li class="nav-item dropdown active">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class='fa fa-address-card' style='font-size:20px;'></i>
                    My Accounts
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  
            
            
                    <a class="dropdown-item" href="{% url 'ecoapp:customerregistration'%}"><i class="fa fa-registered"></i>Register</a> 
                    <a class="dropdown-item" href="{% url 'ecoapp:customerlogin'%}"><i class="fa fa-sign-in"></i>Login</a> 
                
                  </div>
                </li>
                
                
              </ul>
              <form class="form-inline my-2 my-lg-0" action="{%url 'ecoapp:search'%}" method="GET">
                <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search product here" aria-label="Search" required>
                <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </nav>

  
    <hr>
    <script src="{% static 'home/assets/js/repair.js' %}"></script>


    {% block content %}
    {% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    
</body>
</html>

ecomproject/templates/base3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="{% static 'home/assets/css/style1.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'home/assets/css/zoom.css' %}" />
    <style>
      .dot {
        height: 10px;
        width: 10px;
        background-color: rgb(45, 240, 45);
        border-radius: 50%;
        display: inline-block;
        
      }
      {% block css %} {% endblock %}
    </style>
    
<body>
    
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
            <a class="navbar-brand" href="#"><img src="{% static 'home/images/large.png'%} " style="height: 80px; border-radius:50%" ></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
             
              <ul class="navbar-nav mr-auto">
               
                
                
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ecoapp:mycart'%}"><span class="badge badge-info" style="font-size: medium;" ></span><i class="fa fa-shopping-cart" style="font-size:20px;"></i></i>My Cart
                      
                    </a>
                </li>
                
                <li class="nav-item dropdown active">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class='fa fa-address-card' style='font-size:20px;'></i>
                    My Accounts
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if request.user.customer %}
                    <a class="dropdown-item" href="{% url 'ecoapp:customerprofile'%}"><i class="fa fa-user"></i>My Profile</a> 
                    <a class="dropdown-item" href="{% url 'ecoapp:customerlogout'%}"><i class="fa fa-sign-out"></i>Logout</a> 
                    
                    
                    <li class="nav-item active">
                      <a class="nav-link " style="margin-left:350px ; font-size:medium;"><span class="dot"></span>    {{request.user.username}}</a> 
                      
                    </li>
                    {%endif%}
                  </div>

                </li>
                
                
              </ul>
              <form class="form-inline my-2 my-lg-0" action="{%url 'ecoapp:searchbase'%}" method="GET">
                <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search product here" aria-label="Search" required>
                <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </nav>

  
    <hr>
    <script src="{% static 'home/assets/js/repair.js' %}"></script>


    {% block body %}
    {% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    
</body>
</html>

ecomproject/templates/home2.html
{% extends "base2.html" %}
{% block title %}Products List{% endblock %}
{% block content %}
{%load humanize%}

<div class="container-fluid mt-3">
    <!--filter by Category-->
 
    


        <div id="products" class="col-lg-9 mx-auto mb-2">
            <div class="row mx-auto "style="background-color:#ececf0;">
                {% if product_list|length == 0 %}
                    <div class="alert alert-warning col-12">
                        <strong>
                            <h3>No Product Found!</h3>
                        </strong>
                    </div>
                {% elif product_list|length > 0 %}
                    {% for p in product_list %}
                    <div class="card mx-auto mb-3" style="width:18rem;">
                        <div class="m-4">
                        
                                <h4><a href="{% url 'ecoapp:productdetailpage2' p.slug %}">{{p.title}}</a></h4>
                                <img src="{{p.image.url}}" alt="default" class="img-fluid" style="height:200px; object-fit:cover;">
                                <p class="mt-3">Price: <strike> Rs.{{p.marked_price|intcomma}}</strike> Rs. {{p.selling_price|intcomma}} </p>
                                <a href="{% url 'ecoapp:addtocart' p.id %} " class="btn btn-primary" >Add to Cart</a>
                                <a href="{%url 'ecoapp:addtowish' p.id %} " class="btn btn-danger" ><i class="heart fa fa-heart-o"></i></a>
                                <hr>
                        
                        </div>
                    </div>
                    {%endfor%}
                {%endif%}
                    
            </div>
            
                <nav aria-label="...">
                    <ul class="pagination">
                        {% if product_list.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ product_list.previous_page_number }}">Previous</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        {% endif %}
            
                        {% for i in product_list.paginator.page_range %}
                        {% if i == product_list.number %}
                        <li class="page-item active"><a class="page-link">{{i}}</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                        {% endif %}
                        {% endfor %}
            
                        {% if product_list.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
        
            
                    

        </div>
        

    </div>
    
</div>
    
{% endblock %}

ecomproject/templates/mycart.html
{%extends "base2.html" %}
{% load humanize%}
{% block title%}My Cart{%endblock%}
{%block content%}
<style>
    .container{
        background: url("/static/home/images/addtocart.png");
        background-repeat: no-repeat;
        
        height: 100%;
    }
    
</style>
<div class="container">
    {%load static%}
<div class="row">
    <div class="col-md-12">
        <h4>My Cart</h4><hr>
        
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>SN.</th>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                    <th>Action</th>
                </tr>

            </thead>

            <tbody>
                {% for cp in cart.cartproduct_set.all %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><img height="80px" width="100px" src="{{ cp.product.image.url }}" alt="default"></td>
                    <td>{{cp.product.title}}</td>
                    <td>{{cp.rate|intcomma}}</td>
                    <td>{{cp.quantity}}</td>
                    <td>{{cp.subtotal|intcomma}}</td>
                    <td>
                        <a href="{% url 'ecoapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                        <a href="{% url 'ecoapp:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                        <a href="{% url 'ecoapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                    </td>
                </tr>
                {%endfor%}
                <tr>
                    <th colspan="4" class='text-right'>Total</th>
                    <th>Rs.{{ cart.total|intcomma }}</th>
                    {% if cart.cartproduct_set.all%}
                    <th><a href="{% url 'ecoapp:emptycart'%}" class= "btn btn-danger">Empty Cart</a></th>
                    {%endif%}
                </tr>
                {% if cart.cartproduct_set.all%}
                <tr>
                    <th><a class="btn btn-info" href="{% url 'ecoapp:checkout'%}">Checkout</a></th>
                </tr>
                {%endif%}


            </tbody>
        </table>
    </div>
</div>

</div>
{%endblock%}

ecomproject/templates/reviews1.html
{% extends 'base2.html' %}
{% block title %}Customer Reviews{%endblock%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            
        </div>
    </div>
</div>
{%endblock%}

ecomproject/templates/search.html
{% extends "base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>  Your Search Results for"<span class="text-danger"> {{request.GET.keyword}}</span>" </h3>
                <hr>
                {% for result in results%}
                <div class="row">
                    <div class="col-md-4">
                        <div class="img-hover-zoom">
                            <img src="{{result.image.url}}" alt="default",class="img-fluid">
                        </div>
                    </div>
                    <div class="col-md-8">
                        <h4><a href="{% url 'ecoapp:productdetail' result.slug %}">{{result.title}}</a></h4>
                        <p>{{result.description}}</p>
                        

                    </div>
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
{% endblock %}

ecomproject/templates/user_wishlist.html
{%extends "base2.html" %}
{% load humanize%}
{% block title%}My Wish{%endblock%}
{%block content%}
{%load static %}
<style>
  .container{
    background: url("/static/home/images/addtocart.png");
    background-repeat: no-repeat;
    
    height: 100%;
    width: 100%;
}
</style>
<div class = "container">

<div class = "col-8 mx-auto">
  
    <h1 style="font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; ">My Wishlists</h1>
    
    <h5 style="margin-left: 0px; font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; color:green;">Don't let your wishes fade. Add them to E-Mart's wishlist </h5>
    <hr>
    
    {% if messages %}
    <div class="alert alert-warning" alert-{{ message.tags }}" role="alert">
      {% for message in messages  %}
      {{message|safe}} - <a href="{% url 'ecoapp:wishlist' %}" class="alert-link">Your Wishlist</a>.
      {% endfor %}
    </div>
  {% endif %}
    <hr>
    {% if wishlist %}
    {% for product in wishlist %}
    <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{product.image.url}}" class="img-fluid rounded-start" alt="default">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{product.title}}</h5>
              <p class="card-text">{{product.description}}</p>
              <p class="card-text">Rs.{{product.selling_price|intcomma}}</p>
              <a href="{% url 'ecoapp:addtocart' product.id %} " class="btn btn-primary" >Add to Cart</a>
              <a type = "button" class = "btn btn-danger fw500 btn-sm" href="{% url 'ecoapp:user_wishlist' product.id %}"> Remove from wishlist</a>
            </div>
          </div>
        </div>
      </div>

    {%endfor%}
    
    {% else %}
    <p class="card-text">No products have been added to your wishlists</p>



    {%endif%}



    
</div>
</div>
{%endblock%}