ecomproject/ecoapp/urls.py
from django.urls import path 
from .views import *
app_name = "ecoapp"
from .import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url



urlpatterns = [
    #customer url patterns
    path("", views.index, name="index"),
    path("r'^home3/?$'", views.home3, name="home3"),
    path("aboutus/",views.aboutus, name="aboutus"),
   
    path("r'^addcomment/<int:id>/?$'", views.addcomment, name="addcomment"),
    path("contact/", views.contact, name="contact"),
    
    path("home",HomeView.as_view(),name="home"),
    
   
   
    path("about",AboutView.as_view(),name="about"),
    
    path("allproducts/", AllProductView.as_view(),name="allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(),name="productdetail"),
    path("product2/<slug:slug>/", ProductDetailPageView.as_view(),name="productdetailpage2"),
    
    
    

    path("add-to-cart-<int:pro_id>", AddToCartView.as_view(),name="addtocart"),
    
    path("my-cart",MyCartView.as_view(),name="mycart"),
   
    
    path("manage-cart/<int:cp_id>/",ManageCartView.as_view(),name="managecart"),
    
    path("empty-cart", EmptyCartView.as_view(),name="emptycart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path("index",views.index, name="index"),
    path("register",CustomerRegistrationView.as_view(), name="customerregistration"),
    path("logout",CustomerLogoutView.as_view(), name ="customerlogout"),
    path("login/",CustomerLoginView.as_view(), name ="customerlogin"),
    
    path("profile/",CustomerProfileView.as_view(), name ="customerprofile"),
    path("profile/order-<int:pk>/",CustomerOrderDetailView.as_view(),name="customerorderdetail"),
    path("search/", SearchView.as_view(),name="search"),
    path("search2/", SearchBaseView.as_view(),name="searchbase"),
    path("forgot-password/", PasswordForgotView.as_view(), name="passwordforgot"),
    path("password-reset/<email>/<token>/", PasswordResetView.as_view(), name="passwordreset"),



    #admin url pattern
    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-message/",AdminMessageView.as_view(),name="adminmessage"),
    path("admin-home/", AdminHomeView.as_view(),name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),name="orderdetailpage"),
    path("admin-all-orders/", AdminOrderListView.as_view(),name="adminorderlist"),
    path("admin-order-<int:pk>-change/", AdminOrderStatusChangeView.as_view(),name="adminorderstatuschange"),
    path("admin-product-list/", AdminProductView.as_view(), name="adminproductlist"),
    path("admin-product/add/",AdminProductCreateView.as_view(), name ="adminproductcreate"),
    path("productupdate/<pk>/", ProductUpdateView.as_view(), name="product-update"),
    path("products_delete/<int:id>/delete/", product_delete_view, name="product-delete"),
    path("adminlogout",AdminLogoutView.as_view(), name ="adminlogout"),


    #####for wish-list purpose#####################################################################################3
    path("wishlist1/add_to_wishlist/<int:id>/",views.add_to_wishlist, name = "user_wishlist"),
    
    path("wishlist", views.wishlist, name = "wishlist"),
   
   


  
    
]

ecomproject/ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("ecoapp.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomproject/ecoapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.conf import settings


# Create your models here.
class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile  = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username




class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)#onetoone give the object name directly
    
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.full_name








class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)




    @staticmethod
    def get_all_categories():
        return Category.objects.all()
   




    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to="products")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    
    
    warranty = models.CharField(max_length=300,null=True , blank=True)
    warranty_policy = models.CharField(max_length=300,null=True , blank=True)
    view_count = models.PositiveIntegerField(default=0)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)

    @staticmethod
    def get_all_products():
        return Product.objects.all()

    @staticmethod
    def get_all_products_by_categoryid(category_id):
        if category_id:
            return Product.objects.filter(category = category_id)
        
        else:
            return Product.get_all_products()
    


    def __str__(self):
        return self.title

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to = "products/images/")
    
    def __str__(self):
        return self.product.title




class Cart(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return "Cart:" + str(self.id)






class CartProduct(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    rate = models.PositiveIntegerField()

    def __str__(self):
        return "Cart:" + str(self.cart.id) + "CartProduct:" +str(self.id)

ORDER_STATUS = (
    ("Order Received", "Order Received"),# this is one of the property given by the django and first is stored in database and another is shon in the form
    ("Order Processing", "Order Processing"),
    ("On the Way", "on the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)
METHOD = (
    ("Cash On Delivery","Cash On Delivery"),
    ("Khalti Payment","Khalti Payment"),

)

class Order(models.Model):
    
    cart= models.OneToOneField(Cart, on_delete=models.CASCADE)
    order_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null = True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices = ORDER_STATUS, default="Order Received")
    created_at = models.DateTimeField(auto_now=True)
    payment_method = models.CharField(max_length=20, choices = METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(default = False, null= True, blank=True)
    def __str__(self):
        return "Order:" + str(self.id)


class Wish(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, null=True, blank=True)
    email = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return "Wish:" + str(self.id)

class WishProduct(models.Model):
    wish = models.ForeignKey(Wish,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    rate = models.PositiveIntegerField() 

    def __str__(self):
        return "Wish:" + str(self.wish.id) + "WishProduct:" +str(self.id)
    
   













class Comment(models.Model):
    STATUS = (
        ('New','New'),
        ('True','True'),
        ('False','False'),
    )
    product=models.ForeignKey(Product, related_name="comments",on_delete=models.CASCADE)
 
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    
    subject = models.CharField(max_length=50, blank=True)
    comment = models.CharField(max_length=250, blank=True)
    rate = models.IntegerField(default=1)
    ip = models.CharField(max_length=20, blank=True)
    status = models.CharField(max_length=10, choices=STATUS,default='New')
    create_at = models.DateTimeField(auto_now=True)
    update_at = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.user)



  


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']
        
class Contact(models.Model):
    identity = models.CharField(max_length=50, blank=True)
    email = models.EmailField()
    number = models.PositiveIntegerField()
    message = models.TextField()


    def __str__(self):
        return self.identity

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['identity', 'email', 'number','message']

ecomproject/templates/adminpages/adminbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>{%block title%}{%endblock%}</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="{% static 'home/assets/css/style1.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'home/assets/css/zoom.css' %}" /><style>
      .dot {
        height: 10px;
        width: 10px;
        background-color: rgb(45, 240, 45);
        border-radius: 50%;
        display: inline-block;
      }
    </style>

    

</head>
<body>



    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
        <a class="navbar-brand" href="#"><img src="{% static 'home/images/large.png'%} " style="height: 80px; border-radius:50%" ></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'ecoapp:adminhome' %}"><i class="fa fa-home"></i> Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'ecoapp:adminorderlist' %}"><i class="fa fa-first-order"></i>All Orders</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ecoapp:home' %}"><i class="fa fa-user"></i> Customer Site</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ecoapp:adminproductlist' %}"><i class="fa fa-product-hunt"></i> All Products</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ecoapp:adminmessage' %}"><i class="fa fa-envelope"></i> Messages</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ecoapp:adminproductcreate' %}"><i class="fa fa-plus" style=" font-size:20px;";></i>  Add Product</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ecoapp:adminlogout' %}"><i class="fa fa-sign-out"></i> Logout</a>
                  </li>
                  {% if request.user.admin %}
                  
                  
                  <li class="nav-item active">
                    <a class="nav-link " style="margin-left:350px ; font-size:medium;"><span class="dot"></span> {{request.user.username}}</a> 
                    
                    
                  </li>
                  
                  {%endif%}
              
              
            
              
              
            </ul>
            
          </div>
        </nav>


  <hr>
  <script src="{% static 'home/assets/js/repair.js' %}"></script>


  {% block content %}
  {% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
</body>
</html>

ecomproject/templates/adminpages/adminhome.html
{% extends "adminpages/adminbase.html" %}
{%load humanize%}
{% block title %}Admin Home{% endblock %}

{% block content %}<hr>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="container">
            <h3 style="font-family: Georgia, 'Times New Roman', Times, serif;">Pending Orders</h3><hr>
            </div>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>SN</th>
                        <th>Order ID </th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>In Queue Orders</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in pendingorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecoapp:orderdetailpage' order.id%}">#ORDER_{{order.id}}</a></td>
                        <td>{{order.order_by}}</td>

                        <td>{{order.created_at}}</td>
                        <td>{{order.created_at|timesince}} ago</td>

                        <td>Rs. {{order.total|intcomma}}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

ecomproject/templates/adminpages/adminlogin.html
{% extends "base.html" %}
{% block title %}Admin Login{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<style>
    .container-fluid{
        background: url("/static/home/images/admin11.jfif");
        margin-left: 0px;

        
    }
    .user_card {
        width: 610px;
        border-radius: 100px;
        height: 600px;
        margin-left: 500px;
        margin-top: px;
        margin-bottom: auto;
        background: rgba(242, 170, 54, 0.795);
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;
    
      }
</style>

<div class="container-fluid">
    {%load static%}
    <div class="row">
        <div class ="user_card">
            <div class="col-md-6 mx-auto">
             
                <h3 style="text-align: auto; color:white; font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif" >Admin Login</h3><hr>
                <form action = "" method= "POST">
                    {%csrf_token%}
                    
                    {{form.as_p}}<hr>
                    <button class="btn btn-danger">Login as Admin</button>
                    {% if error%}
                    <li style="color:red;">{{error}}</li>
                    {%endif%}

                </form>
            
            </div>
        </div>
    </div>
</div>
{% endblock %}

ecomproject/templates/adminpages/adminmessage.html
{% extends "adminpages/adminbase.html" %}
{%load humanize%}
{% block title %}Admin Home{% endblock %}

{%block content%}
<div class="contanier" style="background-color: rgb(57, 55, 55);">
    <div class="row">

        
        <div class="col-md-12">
            
          
            
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Mobile.no</th>
                        <th style="width:300px;">Messsages</th>
                        <th>Reponse </th>
                        
                    </tr>
    
                </thead>
    
                <tbody>
                    {% for me in message %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        
                        <td>{{me.identity}}</td>
                        <td>{{me.email}}</td>
                        <td>{{me.number}}</td>
                        <td>{{me.message}}</td>
                        <td>
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=new"> <i class="fa fa-envelope" style="font-size:30px;color:red"></i> </a>
                            
                        </td>
                    </tr>

                       
                    </tr>
                    {%endfor%}
                   
    
    
                </tbody>
            </table>
            

















{%endblock%}

ecomproject/templates/adminpages/adminorderlist.html
{% extends "adminpages/adminbase.html" %}
{%load humanize%}
{% block title %}All Orders{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 style="font-family:Georgia, 'Times New Roman', Times, serif;">Orders history</h3>
            <hr>
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th>SN</th>
                            <th>Order ID </th>
                            <th>Customer</th>
                            <th>Ordered On</th>
                            <th>In Queue Orders</th>
                            <th>Amount</th>
                            <th>Order Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in allorders %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td><a href="{% url 'ecoapp:orderdetailpage' order.id%}">#ORDER_{{order.id}}</a></td>
                            <td>{{order.order_by}}</td>

                            <td>{{order.created_at}}</td>
                            <td>{{order.created_at|timesince}} ago</td>

                            <td>Rs. {{order.total|intcomma}}</td>
                            <td>{{order.order_status}}</td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
    </div>
</div>
{%endblock%}

ecomproject/templates/adminpages/adminproductcreate.html
{% extends "adminpages/adminbase.html" %}
{% block title %}Add New Products{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 mx-auto">
            <h3 style="font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">Add New Products</h3>
            <hr>
            <form action="" method="POST", enctype="multipart/form-data" >
                {%csrf_token%}
                {{form.as_p}}
                <button class = "btn btn-danger"> Add Product</button>
            </form>
        </div>
    </div>
</div>

{%endblock%}

ecomproject/templates/adminpages/adminproductlist.html
{% extends "adminpages/adminbase.html" %}
{% block title %}Product Details{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 style="font-family: Georgia, 'Times New Roman', Times, serif;">All products in  E-MART</h3>
            
                <hr>
                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th> SN</th>
                            <th>Product Title</th>
                            <th>Image</th>
                            <th>Prices</th>
                            <th>Views Count</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for p in allproducts %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{p.title}}</td>
                            <td><img src="{{p.image.url}}" style="height:50px;" alt="default"></td>
                            <td>{{p.selling_price}}</td>
                            <td>{{p.view_count}}</td>
                            <td>
                                <a href="{% url 'ecoapp:product-update' p.id %}"> <i class="fa fa-edit" style="font-size:28px"></i></a>
                                <a href="{% url 'ecoapp:product-delete' p.id%}"> <i class="fa fa-trash-o" style="font-size:28px"></i></a>
                                
                                
                            </td>
                            

                        </tr>


                        {%endfor%}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
{% endblock %}

ecomproject/templates/adminpages/adminproductupdate.html
{% extends "adminpages/adminbase.html" %}
{% block title %}Update Product{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 mx-auto">
            <h3 style="font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">Admin update Product</h3>
            <hr>
            <form action="" method="POST", enctype="multipart/form-data" >
                {%csrf_token%}
                {{form.as_p}}
                <button class = "btn btn-danger"> Update</button>
            </form>
        </div>
    </div>
</div>

{%endblock%}

ecomproject/templates/adminpages/orderdetailpage.html
{% extends "adminpages/adminbase.html" %}
{%load humanize%}
{% block title %}Order details{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-5 mx-auto">
                <h3 style="color: rgb(16, 12, 19); text-align:center; font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">Order Detail</h3><hr style="border-width:3px; border-color:black;">
                <p><span class="font-weight-bold">Order ID:  </span>{{ord_obj.id}}</p><hr style=" border-color:black; border-width:1px;">
                <p><span class="font-weight-bold">Order Status:  </span>{{ord_obj.order_status}}</p><hr style=" border-color:black; border-width:1px;">
                <p><span class="font-weight-bold">Ordered On:  </span>{{ord_obj.created_at}}  ({{ord_obj.created_at|timesince}} ago)</p><hr style=" border-color:black; border-width:1px;">
                <p><span class="font-weight-bold">Customer Information:  </span> {{ord_obj.order_by}}, {{ord_obj.mobile}}</p><hr style=" border-color:black; border-width:1px;">
                <p><span class="font-weight-bold">Shipping Address:  </span>{{ord_obj.shipping_address}}, {{ord_obj.email}}</p><hr style=" border-color:black; border-width:1px;">
                <p><span class="font-weight-bold">Payment Information:  </span>{{ord_obj.payment_method}}, ({% if ord_obj.payment_completed %}Payment Completed {% else %}Not Paid{%endif%})</p><hr style=" border-color:black; border-width:1px;">
            </div>
            <div class="col-md-7 mx-auto">

               <h4 style="text-align: center; color:rgb(20, 20, 22); font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">Items Ordered</h4>
               <table class="table">
                <thead class="thead-dark">
                        <tr>
                            <th>SN.</th>
                            <th>Product</th>
                            <th>Rate</th>
                            <th>Quantity</th>
                            <th>Subtotal</th>
                            
                        </tr>
        
                    </thead>
    
    
                        <tbody>
                            {% for cp in ord_obj.cart.cartproduct_set.all%}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td><a target="_blank" href="{% url 'ecoapp:productdetail' cp.product.slug%}">{{cp.product.title}} {{cp.product.id}}</a></td>
                                <td>{{cp.rate}}</td>
                                <td>{{cp.quantity}}</td>
                                <td>Rs. {{cp.subtotal|intcomma}}</td>
                            </tr>

                            {%endfor%}

                            <tr>
                                <th colspan="4" class="text-right">Total:</th>
                                <th>Rs. {{ord_obj.total|intcomma}}</th>
                            </tr>
            
                        </tbody>
                </table>
            </div>
            <div class="col-md-8 mx-auto" style="margin-top: 100px;;">
                <form action="{% url 'ecoapp:adminorderstatuschange' ord_obj.id%}" method="POST">
                    {% csrf_token %}
                    <select style="font-size:26px; background-color:rgb(226, 171, 43)"  name="status">
                        {%for i,j in allstatus%}
                            <option  value="{{i}}"{% if i == ord_obj.order_status %}selected{% endif %}>{{j}}</option>
                        {%endfor%}

                        

                    </select>
                    <button class="btn btn-danger" style="font-size: 22px;">Change Status</button>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

ecomproject/templates/adminpages/product_delete.html
{% extends "adminpages/adminbase.html" %}
{% block title %}Delete Product{% endblock %}

{% block content %}
<div class="container-fluid" style=" height:500px; width:1000px;">

    <form action='.' method='POST'>
        {% csrf_token %}
        <h1 style="margin-top: 90px; margin-left:0px; font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; font-size:28px;">Do you want to delete the product "{{ object.title }}"?</h1>
        <p style="margin-left: 340px; font-size:28px; margin-top:50px;"><input type='submit' value='Yes' />  <a href="{% url 'ecoapp:adminproductlist' %}">Cancel</a></p>

    </form>
</div>

{%endblock%}